name: Build and deploy container app to Azure Web App - mdm-footwear-kethehar

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Die lokalen permissions hier wurden entfernt, damit die globalen (packages: write) gelten

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # Hier den Namen beibehalten
          tags: ghcr.io/kethehar/djl-footwear-classification:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0EEB92B7EF524968B2EA61F337506437 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6FD505AE694443268B6BDBB1B6F7B3A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2BBD7DA3C3034CF7AC1E517251EF86FF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mdm-footwear-kethehar'
          slot-name: 'Production'
          # WICHTIG: Muss exakt mit dem Tag von oben übereinstimmen!
          images: 'ghcr.io/kethehar/djl-footwear-classification:latest'
